// src/lib/styles.js
// Shared inline-style tokens for the portal shell and pages. Extracted from
// PomeloTechOpsPortal.jsx; import as `import { S } from '../lib/styles.js'`.
// New components should prefer these over ad-hoc style objects so spacing and
// color stay consistent with the theme variables in ThemeContext.

export const S = {
  app: {
    fontFamily: "'Inter', sans-serif",
    background: 'var(--bg-page)',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    color: 'var(--text-primary)',
  },
  nav: {
    background: 'var(--bg-nav)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 28px',
    height: '60px',
    borderBottom: '1px solid var(--border-default)',
    boxShadow: 'var(--shadow-card)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  navLogo: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  navLogoText: {
    color: 'var(--text-primary)',
    fontWeight: 900,
    fontSize: '17px',
    letterSpacing: '0.02em',
  },
  navLogoSub: {
    color: 'var(--accent-primary)',
    fontWeight: 700,
    fontSize: '11px',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    marginTop: '-2px',
  },
  navTabs: {
    display: 'flex',
    alignItems: 'center',
    gap: '2px',
  },
  navTab: active => ({
    padding: '8px 12px',
    border: 'none',
    background: 'transparent',
    color: active ? 'var(--text-primary)' : 'var(--text-secondary)',
    fontFamily: "'Inter', sans-serif",
    fontSize: '13px',
    fontWeight: active ? 600 : 500,
    cursor: 'pointer',
    transition: 'all 0.15s',
    whiteSpace: 'nowrap',
    position: 'relative',
    boxShadow: active ? 'inset 0 -1.5px 0 0 var(--accent-primary)' : 'none',
    borderRadius: '0',
  }),
  navUser: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: 'var(--text-secondary)',
    fontSize: '13px',
  },
  avatar: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    background: 'var(--accent-primary)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#fff',
    fontWeight: 700,
    fontSize: '13px',
  },
  main: {
    flex: 1,
    padding: '32px 28px',
    maxWidth: '1100px',
    margin: '0 auto',
    width: '100%',
    boxSizing: 'border-box',
  },
  pageTitle: {
    fontSize: '24px',
    fontWeight: 900,
    color: 'var(--text-primary)',
    marginBottom: '4px',
  },
  pageSub: {
    fontSize: '14px',
    color: 'var(--text-secondary)',
    marginBottom: '28px',
  },
  card: {
    background: 'var(--bg-surface)',
    borderRadius: 'var(--radius-lg)',
    border: '1px solid var(--border-default)',
    padding: '24px',
    boxShadow: 'var(--shadow-card)',
  },
  orangeBtn: {
    background: 'var(--accent-primary)',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '10px 20px',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontSize: '14px',
    cursor: 'pointer',
    transition: 'background 0.15s',
  },
  ghostBtn: {
    background: 'transparent',
    color: 'var(--accent-primary)',
    border: '1.5px solid var(--accent-primary)',
    borderRadius: '8px',
    padding: '8px 16px',
    fontFamily: "'Inter', sans-serif",
    fontWeight: 700,
    fontSize: '13px',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  // Compact icon button used by editor toolbars (Doc Studio's RichTextarea).
  toolbarBtn: {
    minWidth: '28px',
    height: '28px',
    padding: '0 7px',
    borderRadius: '6px',
    border: '1px solid transparent',
    background: 'transparent',
    color: 'var(--text-secondary)',
    cursor: 'pointer',
    fontSize: '12px',
    fontWeight: 700,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: "'Inter', sans-serif",
  },
  label: {
    fontSize: '12px',
    fontWeight: 700,
    color: 'var(--text-secondary)',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
    marginBottom: '6px',
    display: 'block',
  },
  input: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1.5px solid var(--border-default)',
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    color: 'var(--text-primary)',
    background: 'var(--bg-input)',
    outline: 'none',
    boxSizing: 'border-box',
    transition: 'border-color 0.15s',
  },
  textarea: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1.5px solid var(--border-default)',
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    color: 'var(--text-primary)',
    background: 'var(--bg-input)',
    outline: 'none',
    boxSizing: 'border-box',
    resize: 'vertical',
    minHeight: '100px',
    transition: 'border-color 0.15s',
  },
  // Compact right-aligned input for inline field edits in the ticket Details panel.
  inlineEdit: {
    padding: '3px 8px',
    borderRadius: '5px',
    border: '1px solid var(--border-default)',
    background: 'var(--bg-page)',
    fontSize: '13px',
    fontWeight: 700,
    color: 'var(--text-primary)',
    textAlign: 'right',
    outline: 'none',
    maxWidth: '190px',
    fontFamily: "'Inter', sans-serif",
  },
  select: {
    width: '100%',
    padding: '10px 14px',
    borderRadius: '8px',
    border: '1.5px solid var(--border-default)',
    fontFamily: "'Inter', sans-serif",
    fontSize: '14px',
    color: 'var(--text-primary)',
    background: 'var(--bg-input)',
    outline: 'none',
    boxSizing: 'border-box',
    cursor: 'pointer',
    appearance: 'none',
  },
  badge: color => ({
    display: 'inline-block',
    padding: '3px 10px',
    borderRadius: '100px',
    background: color + '18',
    color: color,
    fontSize: '11px',
    fontWeight: 700,
    letterSpacing: '0.04em',
  }),
  statCard: {
    background: 'var(--bg-surface)',
    borderRadius: '12px',
    border: '1px solid var(--border-default)',
    padding: '20px 24px',
    boxShadow: 'var(--shadow-card)',
  },
  statNum: {
    fontSize: '36px',
    fontWeight: 900,
    color: 'var(--text-primary)',
    lineHeight: 1,
  },
  statLabel: {
    fontSize: '13px',
    color: 'var(--text-secondary)',
    marginTop: '4px',
  },
  footer: {
    background: 'var(--bg-surface)',
    color: 'var(--text-muted)',
    textAlign: 'center',
    padding: '16px 24px',
    fontSize: '13px',
    marginTop: 'auto',
    borderTop: '1px solid var(--border-default)',
  },
};
